- .gitignore
- src/main/java/io/fabric8/elasticsearch/plugin/ConfigurationSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardACL.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/UserProjectCache.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/UserProjectCacheMapAdapter.java
This PR adds the evaluation of a users ability to see the operations logs based on their role of cluster-admin.
@sosiouxme @ewolinetz @jimmidyson  please review.
Note: once the fabric8 client supports SAR, the isClusterAdmin can be rewritten.
> Evaluate if a user should see operations index

- README.md
- src/main/java/io/fabric8/elasticsearch/plugin/ConfigurationSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardACL.java
Curator is the Elasticsearch tool that deletes/archives old indices.  It needs very specific access, so we need to create a new user and give that user very specific access.
> add support for a curator user for ES

- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
@jcantrill ptal
`indexPatterns` list gets passed along to delete patterns from the contents
> removing all alias if user is not cluster-admin

- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
Resolves NPE as observed when resolving BZ 1377187 :
```
[2016-09-20 21:24:09,017][ERROR][io.fabric8.elasticsearch.plugin.acl.DynamicACLFilter] [Demogoblin] Error retrieving project list for 'xiazhao@redhat.com'
java.lang.NullPointerException
at io.fabric8.elasticsearch.plugin.kibana.KibanaSeed.getDefaultIndex(KibanaSeed.java:186)
at io.fabric8.elasticsearch.plugin.kibana.KibanaSeed.setDashboards(KibanaSeed.java:121)
at io.fabric8.elasticsearch.plugin.acl.DynamicACLFilter.updateCache(DynamicACLFilter.java:189)
at io.fabric8.elasticsearch.plugin.acl.DynamicACLFilter.process(DynamicACLFilter.java:153)
at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:283)
at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:180)
at …
```
> Checking for null source when checking default kibana index pattern

- src/main/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardRoles.java
https://github.com/fabric8io/openshift-elasticsearch-plugin/issues/46
Remove these rules which were granting too much access:
```
"gen_kibana_45c571a156ddcef41351a713bcddee5ba7e95460":{
"cluster":[
-		"cluster:monitor/nodes/info",
-		"cluster:monitor/health"
],
"indices":{
-		"*":{
-			"*":[
-				"indices:admin/validate/query*",
-				"indices:admin/get*",
-				"indices:admin/mappings/fields/get*",
-				"indices:data/read*"
-			]
-		},
"?kibana?45c571a156ddcef41351a713bcddee5ba7e95460":{
"*":[
"indices:*"
]
}
}
}
```
> Access allows users to see indices in other projects #46

- src/main/java/io/fabric8/elasticsearch/plugin/KibanaUserReindexFilter.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenShiftElasticSearchPlugin.java
- src/main/java/io/fabric8/elasticsearch/plugin/PluginClient.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
- src/main/java/io/fabric8/elasticsearch/plugin/filter/FieldStatsResponseFilter.java
- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
- src/main/java/io/fabric8/elasticsearch/rest/KibanaUserRestHandler.java
- src/main/java/io/fabric8/elasticsearch/util/RequestUtils.java
- src/test/java/io/fabric8/elasticsearch/plugin/OpenShiftElasticSearchPluginTest.java
- src/test/java/io/fabric8/elasticsearch/plugin/filter/FieldStatsResponseFilterTest.java
- src/test/java/io/fabric8/elasticsearch/util/RequestUtilsTest.java
This PR fixes the error message displayed to users in kibana:
* Creates mappings only for indices that exist
* Modifies the response when fieldstat call is made
> bug 1456413. Fix security error message for patterns with no indexes

- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
If the user specifies an index pattern in Kibana like "project.*"
because they want to have a search for all projects that they
have access to, this will cause an exception in the openshift
elasticsearch plugin string handling.
The fix is to perform better string bounds checking.
> project.* index pattern causes exception

- src/main/java/io/fabric8/elasticsearch/plugin/KibanaUserReindexAction.java
- src/main/java/io/fabric8/elasticsearch/plugin/kibana/GetResultBuilder.java
- src/test/java/io/fabric8/elasticsearch/plugin/kibana/GetResultBuilderTest.java
Backport of #83 
(cherry picked from commit 56f6e8bff24bab6c0b7b027701e6763d79b6d556)
> bug 1457232. Fix null pointer in KibanaUserReindexAction

- README.md
- pom.xml
- src/main/java/io/fabric8/elasticsearch/plugin/ConfigurationSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/KibanaIndexMode.java
- src/main/java/io/fabric8/elasticsearch/plugin/KibanaUserReindexFilter.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenshiftClientFactory.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenshiftRequestContextFactory.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardRoles.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardRolesMapping.java
- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
- src/main/java/io/fabric8/elasticsearch/rest/KibanaUserRestHandler.java
- src/main/java/io/fabric8/elasticsearch/util/RequestUtils.java
- src/test/java/io/fabric8/elasticsearch/plugin/OpenshiftRequestContextFactoryTest.java
- src/test/java/io/fabric8/elasticsearch/plugin/Samples.java
- src/test/java/io/fabric8/elasticsearch/plugin/TestUtils.java
- src/test/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardRoleACLTest.java
- src/test/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardRolesMappingACLTest.java
- src/test/resources/io/fabric8/elasticsearch/plugin/roles_ops_shared_kibana_index.yml
- src/test/resources/io/fabric8/elasticsearch/plugin/roles_ops_shared_kibana_index_with_unique.yml
- src/test/resources/io/fabric8/elasticsearch/plugin/rolesmapping_ops_shared_kibana_index.yml
This is a result of a discussion I had with @portante and ops regarding https://bugzilla.redhat.com/show_bug.cgi?id=1427254
Justification is ops users already have access to the entire cluster and this would allow them to share dashboards and visualizations unrestricted.
> bz 1427254  Kibana Index Mode

- src/main/java/io/fabric8/elasticsearch/plugin/ConfigurationSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/KibanaIndexMode.java
- src/main/java/io/fabric8/elasticsearch/plugin/PluginSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/BaseRolesMappingSyncStrategy.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/BaseRolesSyncStrategy.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/ProjectRolesMappingSyncStrategy.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/ProjectRolesSyncStrategy.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/RolesMappingSyncStrategy.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/RolesSyncStrategy.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardRoles.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardRolesMapping.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardSyncStrategyFactory.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/UserRolesMappingSyncStrategy.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/UserRolesSyncStrategy.java
- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
- src/test/java/io/fabric8/elasticsearch/plugin/PluginSettingsTest.java
- src/test/java/io/fabric8/elasticsearch/plugin/Samples.java
- src/test/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardRoleACLTest.java
- src/test/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardRolesMappingACLTest.java
- src/test/resources/io/fabric8/elasticsearch/plugin/user_role_with_shared_kibana_index_with_unique.yml
- src/test/resources/io/fabric8/elasticsearch/plugin/user_rolesmapping_shared_ops_kibana_index_with_unique.yml
This PR introduces:
* ACL documents generated based on roles per user instead of per project [1]
* Resolves issue where user is unable to query across multiple indexes
The configuration option `openshift.acl.role_strategy` allows you to switch between generating roles per project where running queries across multiple project indices is not possible and generating roles per user.  The later creates proper role permissions to query across the indices you own.  I don't see us promoting or encouraging us of project role strategy going forward; this was a refactoring convenience to confirm everything was properly tested and backwards compatible.
[1] https://github.com/jcantrill/openshift-elasticsearch-plugin/blob/60f9d06520b73bcbd8bb74bfd17b71f89ac3d6ac/src/test/resources/io/fabric8/elasticsear …
> modify roles to be user based so all of a users indexes are visible in a single query

- .gitignore
- src/main/java/io/fabric8/elasticsearch/plugin/acl/RolesSyncStrategy.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/UserRolesSyncStrategy.java
- src/test/resources/io/fabric8/elasticsearch/plugin/user_role_with_shared_kibana_index_with_unique.yml
The PR:
* Allows specification of cluster permissions for non-ops users
* Enables fixing of exporting ui objects.
cc @portante
> bug 1463436. Allow defining cluster perms to allow export of ui objects

- src/main/java/io/fabric8/elasticsearch/plugin/PluginClient.java
- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
- src/main/java/io/fabric8/elasticsearch/util/IndexUtil.java
- src/test/java/io/fabric8/elasticsearch/util/IndexUtilTest.java
This PR
* Modifies seeding code to only create index-patterns and alias when they do not already exist
* Requires an additional permission for the role to allow write to the kibana index
> bug 1476062. Only seed documents when they are missing

- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
This PR fixes the issue where .operations is missing from the .all alias
Test before fix:
```$ PUBLIC_MASTER_URL=https://192.168.122.89:8443 bundle exec cucumber --tags @test
#encoding: utf-8
Feature: The openshift-elasticsearch-plugin initializes access
control to indices in the cluster and Kibana UI objects
@kibana @test
Scenario: The .all alias references all indices                 # features/openshift-elasticsearch-plugin.feature:27
Given a user with the role of operations                      # features/step_definitions/policy_steps.rb:1
And the .all alias initially does not exist                   # features/step_definitions/elasticsearch_steps.rb:7
And logs were collected for the logging project               # features/step_definitions/elasticsearch_steps.rb:1
When they log into …
```
> bug 1490719. Operations missing from .all alias

- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
This PR fixes 1519705:
* Alias .operations if operations user and .operation indices exist
```
[2017-12-04 21:02:58,033][ERROR][io.fabric8.elasticsearch.plugin.kibana.KibanaSeed] Error executing Alias request
[.operations.*] IndexNotFoundException[no such index]
```
> fix 1519705. All alias shows now indices

- README.md
- src/main/java/io/fabric8/elasticsearch/plugin/OpenShiftElasticSearchConfigurationException.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenshiftRequestContextFactory.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardRolesMapping.java
- src/main/java/io/fabric8/elasticsearch/plugin/auth/FileAuthenticationBackend.java
- src/main/java/io/fabric8/elasticsearch/util/RequestUtils.java
- src/test/java/io/fabric8/elasticsearch/plugin/Samples.java
- src/test/java/io/fabric8/elasticsearch/plugin/auth/FileAuthenticationBackendTest.java
- src/test/resources/io/fabric8/elasticsearch/plugin/passwords.yml
fixup support for retrieving metrics
This PR:
* Adds support for a custom 'Basic' authentication to handle openshift service accounts from file
* removes user header from requests where no bearer token is provided
* no longer returns early if no bearer token exists. depends on additional SG processing
> bug 1537857. Remove user header for requests without tokens and

- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
This PR:
* fixes #104 by skipping seeding if the default Kibana does not exist
> fix #104. Skip Kibana seeding if no default Kibana index exists

- src/it/java/io/fabric8/elasticsearch/ElasticsearchIntegrationTest.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenshiftAPIService.java
- src/test/java/io/fabric8/elasticsearch/plugin/OpenshiftAPIServiceTest.java
This PR fixes https://jira.coreos.com/browse/LOG-226 
which allows using a nonResourceURL to check SARs.  This will allow us to rely on the clusterrole provided by the cluster-monitoring-operator
> LOG-226. Allow SAR of nonResourcedURL

- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
This PR fixes https://bugzilla.redhat.com/show_bug.cgi?id=1667801 by removing the explicit replica setting when creating the index and let it rely on the template
> bug 1694884. Don't explicitly define kibana index replica

- src/main/java/io/fabric8/elasticsearch/plugin/OpenShiftElasticSearchPlugin.java
if we use the openshift.acl.expire_in_millis in elasticsearch.yml, we will get some error log. Elasticsearch can not start .
```
[2019-04-22T02:49:16,878][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [logging-es-data-master-dgogq2rs] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [openshift.acl.expire_in_millis] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
```
> declare OPENSHIFT_ACL_EXPIRE_IN_MILLIS in OpenShiftElasticSearchPlugin

- src/main/java/io/fabric8/elasticsearch/plugin/ConfigurationSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenShiftElasticSearchPlugin.java
If we want to use some configuration items, we should declare them on the OpenShiftElasticSearchPlugin.
I did some proof-reading.
> collate configuration items

- pom.xml
- src/main/java/io/fabric8/elasticsearch/plugin/OpenshiftAPIService.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenshiftRequestContextFactory.java
This PR explicitly sets a user's token on the request as a header when making calls to the Openshift API server to resolve an issue where there was unexpected response when executing a SAR
> fix missing token for OpenShiftAPIService requests

- pom.xml
- src/it/java/io/fabric8/elasticsearch/ElasticsearchIntegrationTest.java
- src/it/java/io/fabric8/elasticsearch/KibanaIndexModeIntegrationBase.java
- src/it/java/io/fabric8/elasticsearch/KibanaIndexModeSharedOpsIntegrationTest.java
- src/main/java/io/fabric8/elasticsearch/plugin/PluginClient.java
- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
This PR fixes https://bugzilla.redhat.com/show_bug.cgi?id=1746377 by:
* retrieving and comparing against a list of indices instead of using a search result
> Bug 1746377: Fetch indices instead of search to seed index patterns

- pom.xml
This PR disables http/2 to resolve issues running an alternate nodes from typical RH
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1835396
> Bug 1835396: Disable http/2
