fabric8io/openshift-elasticsearch-plugin

- README.md
- src/main/java/io/fabric8/elasticsearch/plugin/ConfigurationSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenShiftElasticSearchPlugin.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenShiftElasticSearchService.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardACL.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/UserProjectCache.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/UserProjectCacheMapAdapter.java
- src/main/resources/es-plugin.properties
- src/test/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardACLTest.java
- src/test/resources/io/fabric8/elasticsearch/plugin/searchguard_acl_with_openshift_projects.json
@jimmidyson please review.  Updates for name changes and introduction of config settings to allow for defaults, etc.
> Update classes and documentation to reflect repo name change

- pom.xml
- samples/elasticsearch.yml
> fix pom to point to the renamed repo

- src/main/java/io/fabric8/elasticsearch/plugin/ActionForbiddenActionFilter.java
- src/main/java/io/fabric8/elasticsearch/plugin/ForbiddenException.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenShiftElasticSearchPlugin.java
@jimmidyson @sosiouxme @ewolinetz  Replace the 500 response with a 403.  Please review
> Return 403 response

- src/main/java/io/fabric8/elasticsearch/plugin/ConfigurationSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenShiftElasticSearchModule.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenShiftElasticSearchPlugin.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenShiftElasticSearchService.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/ACLNotifierService.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/DefaultACLNotifierService.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardACLActionRequestListener.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardACLRequestActionFilter.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/UserProjectCacheMapAdapter.java
@jimmidyson @ewolinetz  @sosiouxme  Replaced the thread.sleep with notification when ACL is loaded .  Please review
> Add notification when loading ACL

- pom.xml
- src/main/java/io/fabric8/elasticsearch/plugin/ConfigurationSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/HTTPSProxyClientCertAuthenticator.java
- src/main/java/io/fabric8/elasticsearch/plugin/UnauthorizedException.java
- src/test/java/io/fabric8/elasticsearch/plugin/HTTPSProxyClientCertAuthenticatorIntegrationTest.java
- src/test/java/io/fabric8/elasticsearch/plugin/HTTPSProxyClientCertAuthenticatorTest.java
And make return 401 instead of 500 when cert auth fails.  @sosiouxme @ewolinetz @jimmidyson  please review
> Impl to auth by proxy header and fall back to client cert

- src/main/java/io/fabric8/elasticsearch/plugin/KibanaUserReindexAction.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
- src/main/java/io/fabric8/elasticsearch/plugin/kibana/DocumentBuilder.java
- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
@jcantrill @sosiouxme @jimmidyson PTAL.
We now correctly seed the kibana index for a user based on their OS project access.
We also remove a user and reset their default index if their previous default was removed due to access being removed on OS.
FYI: all but the latest 3 commits are throw away :)
> Fix kibana seeding

- README.md
- samples/sg_actiongroups.yml
- samples/sg_config.yml
- samples/sg_roles.yml
- samples/sg_rolesmapping.yml
> Updating readme for 2.3.3.x changes

- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
@jcantrill this is the es 2.3 version of #33
> ensuring to use empty scope for checking if user is cluster-admin

- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
Cherry picked from https://github.com/fabric8io/openshift-elasticsearch-plugin/pull/35
> removing all alias if user is not cluster-admin

- pom.xml
> bumping version of es to 2.3.5

- src/main/java/io/fabric8/elasticsearch/plugin/ActionForbiddenActionFilter.java
check NPE in ActionForbiddenActionFilter
> check NPE in ActionForbiddenActionFilter

- pom.xml
> bumping to es 2.4.1

- pom.xml
@jcantrill @ewolinetz ptal
[test]
> bump version to 2.4.4 for ES 2.4.4 and other ES related components

- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
I am unable to reproduce locally and I'm guessing this is the only place where it could happen.  Searching through the ES code shows that  it will throw such an exception only on creates.
> fixes 1416210. Check for existence of index before trying to create

- pom.xml
> fix the sg dependency

- .gitignore
- src/main/java/io/fabric8/elasticsearch/plugin/ConfigurationSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
This PR fixes:
* Concurrency issues while seeding initial ACL
* Deletes SG index on start up if exists
* Adds state to seeding ACLs
* Forces SG to load all ACL docs on write update
* Updates debug logs to pretty print doc info
> bug 1431551. Node does not survive upgrade

- src/main/java/io/fabric8/elasticsearch/plugin/ConfigurationSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
Easier version to read of #68 for 2.4.4.  I was unable to cherry-pick straight over
cc @ewolinetz @richm
> bug 1421551. Node does not survive upgrade for 2.4.4 ES

- src/main/java/io/fabric8/elasticsearch/plugin/ConfigurationSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
> bug 1446217. Use SAR to determine isOperationalUser

- src/main/java/io/fabric8/elasticsearch/plugin/ConfigurationSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
(cherry picked from commit 6ec1e3aec4107fb6dc92c0c84c9c0bc1f8830312)
> bug 1455691. Use SAR to determine isOperationalUser

- src/main/java/io/fabric8/elasticsearch/plugin/KibanaUserReindexAction.java
- src/main/java/io/fabric8/elasticsearch/plugin/kibana/GetResultBuilder.java
- src/test/java/io/fabric8/elasticsearch/plugin/kibana/GetResultBuilderTest.java
> bug 1459221. Fix null pointer in KibanaUserReindexAction

- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
bug 1473153. Always add .all for ops users
Only the latest commit is of interest.  The first commit should be merged before this PR.
> bug 1473153. Always add .all for ops users

- src/main/java/io/fabric8/elasticsearch/plugin/filter/FieldStatsResponseFilter.java
This PR will fix the "[security_exception] no permissions for indices:data/read/msearch" by handling the empty indices when "data/read/field_stats" is called. A understandable error message is show to the user.
> fix empty indices for indices:data/read/field_stats

- src/main/java/io/fabric8/elasticsearch/plugin/OpenshiftRequestContextFactory.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/BaseRolesSyncStrategy.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/UserRolesSyncStrategy.java
- src/main/java/io/fabric8/elasticsearch/util/RequestUtils.java
- src/test/java/io/fabric8/elasticsearch/plugin/OpenshiftRequestContextFactoryTest.java
- src/test/java/io/fabric8/elasticsearch/plugin/acl/BaseRolesSyncStrategyTest.java
- src/test/java/io/fabric8/elasticsearch/plugin/acl/UserRolesSyncStrategyTest.java
This PR fixes BZ1491227:
* Modifying the request header to convert backslash to forward
* Fixes role and role mapping generation to handle slashes
> bug 1491227. Modify request if user has back slash

- pom.xml
- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
> Upstream 241 11

- pom.xml
Add openssl dependent libraries
> add use of openssl for keystore

- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
Fixes #122 by removing all alias creation from plugin since we do that using templates
> fix #122. remove alias creation from plugin

- src/main/java/io/fabric8/elasticsearch/plugin/ConfigurationSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenshiftRequestContextFactory.java
- src/main/java/io/fabric8/elasticsearch/plugin/PluginClient.java
- src/main/java/io/fabric8/elasticsearch/plugin/PluginSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
- src/test/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeedTest.java
This PR
* Reduces the index-patterns for cluster-admins to a finite set based on config
> reduce index-patterns for cluster-admins

- README.md
This PR fixes the README documentation
> Fix README to ref 5.x

- src/main/java/io/fabric8/elasticsearch/plugin/ConfigurationSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenshiftRequestContextFactory.java
- src/main/java/io/fabric8/elasticsearch/util/RequestUtils.java
> fix apidoc gen failures

- pom.xml
- src/main/java/io/fabric8/elasticsearch/util/RequestUtils.java
- src/test/java/io/fabric8/elasticsearch/plugin/OpenshiftRequestContextFactoryTest.java
@richm @ewolinetz @jcantrill  Please, tell me what you think
> Support oauth tokens from x-forwarded-access-token

- pom.xml
- src/main/java/io/fabric8/elasticsearch/util/RequestUtils.java
- src/test/java/io/fabric8/elasticsearch/plugin/OpenshiftRequestContextFactoryTest.java
This reverts commit 1c4136ce9ae3df17ea2cc2b42a90b46081b5540e.
Revert #145 to correct default version first
> Revert "support oauth tokens from x-forwarded-access-token"

- src/main/java/io/fabric8/elasticsearch/plugin/OpenshiftRequestContextFactory.java
- src/main/java/io/fabric8/elasticsearch/util/RequestUtils.java
- src/test/java/io/fabric8/elasticsearch/plugin/OpenshiftRequestContextFactoryTest.java
Found an issue where the access token was being skipped even though it was properly provided by the new proxy
> fix some strange issue using the fowarded access token

- README.md
- src/main/java/io/fabric8/elasticsearch/plugin/ConfigurationSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenShiftElasticSearchPlugin.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenShiftElasticSearchService.java
- src/main/java/io/fabric8/elasticsearch/plugin/OpenshiftAPIService.java
- src/main/java/io/fabric8/elasticsearch/plugin/PluginClient.java
- src/main/java/io/fabric8/elasticsearch/plugin/PluginServiceFactory.java
- src/main/java/io/fabric8/elasticsearch/plugin/PluginSettings.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/DynamicACLFilter.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardRolesMapping.java
- src/main/java/io/fabric8/elasticsearch/plugin/acl/SearchGuardSyncStrategyFactory.java
- src/main/java/io/fabric8/elasticsearch/plugin/auth/OpenShiftTokenAuthentication.java
- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
- src/main/java/io/fabric8/elasticsearch/util/RequestUtils.java
- src/test/java/io/fabric8/elasticsearch/plugin/auth/OpenShiftTokenAuthenticationTest.java
- src/test/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeedTest.java
- src/test/resources/sgconfig/config.yml
Enhancement to add bearer token auth https://jira.coreos.com/browse/LOG-192
This PR additionally allows us to add static groups which should also satisfy the prometheus metrics usecase and removing the proxy for that use.
> enhancement #LOG192. Impl Openshift Token Auth

- src/it/java/io/fabric8/elasticsearch/GeneralUserWorkflowIntegrationTest.java
- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaUtils.java
- src/test/java/io/fabric8/elasticsearch/plugin/kibana/KibanaUtilsTest.java
This PR fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1679613
By handling null default Index
cc @ewolinetz
> bug 1679613. Handle null defaultIndex

- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeed.java
- src/main/java/io/fabric8/elasticsearch/plugin/kibana/KibanaUtils.java
- src/test/java/io/fabric8/elasticsearch/plugin/kibana/KibanaSeedTest.java
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1694884
> bug 1694884. Default kibana index if blank

- pom.xml
Bump kubeclient-openshift-uberjar to resolve https://bugzilla.redhat.com/show_bug.cgi?id=1730588
> bump kubeclient-openshift-uberjar to 4.3.0

- pom.xml
To resolve https://bugzilla.redhat.com/show_bug.cgi?id=1730588
> 431 kubeclient

- pom.xml
Resolves:
* https://bugzilla.redhat.com/show_bug.cgi?id=1745011
* https://bugzilla.redhat.com/show_bug.cgi?id=1738406
* https://bugzilla.redhat.com/show_bug.cgi?id=1738404
> Bug 1738411: Bump kubernetes-client to 4.4.2

- pom.xml
Resolve: https://bugzilla.redhat.com/show_bug.cgi?id=1762572
>  Bug 1762572: bump kubernetes-client

- src/main/java/io/fabric8/elasticsearch/plugin/OpenshiftAPIService.java
This fixes https://bugzilla.redhat.com/show_bug.cgi?id=1835396
> Disable HTTP2 in communication with OpenShift
